pipeline {
  agent {
    kubernetes
    {
    label 'java-app'
    }
   }
  stages {
    stage('Test') {

      steps {
     container('maven') {
       echo "${cucumber_tag}"
        sh "mvn test"
        }
      }
    }
  }
}
